spring:
  data:
    mongodb:
      host: 192.168.1.20
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27000

server:
  context-path: /uaa
  port: 5000
